version: "3.9"
services:
  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fusionems
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  opa:
    image: openpolicyagent/opa:0.67.0
    command: ["run","--server","--addr","0.0.0.0:8181","/policies"]
    volumes:
      - ./opa/policies:/policies:ro
    ports: ["8181:8181"]
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.108.0
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otel/config.yaml:/etc/otelcol/config.yaml:ro
    ports: ["4318:4318","8889:8889"]
  prometheus:
    image: prom/prometheus:v2.53.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports: ["9090:9090"]
  grafana:
    image: grafana/grafana:11.1.0
    ports: ["3001:3000"]
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
