global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: backend
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - backend:8000
        labels:
          service: fusionems
          component: backend

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
